// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkrDO48oZE2JMGfCv14oAdlQ6SSJlKPHA',
    appId: '1:919702854036:web:fe962ba5e7bd3fe16ed781',
    messagingSenderId: '919702854036',
    projectId: 'alsharyah-private',
    authDomain: 'alsharyah-private.firebaseapp.com',
    storageBucket: 'alsharyah-private.appspot.com',
    measurementId: 'G-ZWDGH4SKVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfbeS0sTOe1vitYwDOpJYXFqmDapuPySc',
    appId: '1:919702854036:android:e6bf8e5b88b243556ed781',
    messagingSenderId: '919702854036',
    projectId: 'alsharyah-private',
    storageBucket: 'alsharyah-private.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1g2cwYN6B4-TecNjxM9Hwma27FrLedxc',
    appId: '1:919702854036:ios:f61468dd8a2487376ed781',
    messagingSenderId: '919702854036',
    projectId: 'alsharyah-private',
    storageBucket: 'alsharyah-private.appspot.com',
    iosClientId:
        '919702854036-k0fkc40h04q4fkn5ra4f1o6trtlsvqd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.alsharyah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1g2cwYN6B4-TecNjxM9Hwma27FrLedxc',
    appId: '1:919702854036:ios:f61468dd8a2487376ed781',
    messagingSenderId: '919702854036',
    projectId: 'alsharyah-private',
    storageBucket: 'alsharyah-private.appspot.com',
    iosClientId:
        '919702854036-k0fkc40h04q4fkn5ra4f1o6trtlsvqd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.alsharyah',
  );
}
